import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "./Providers";
import NextTopLoader from 'nextjs-toploader';
import Header from "@/components/Header";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <NextTopLoader 
            color="#2299DD"
            height={1}
            showSpinner={false}
            shadow={false} />
            <Header />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
